# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  Glad_config = debug
  ImGui_config = debug
  engine_config = debug
  sandbox_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  Glad_config = release
  ImGui_config = release
  engine_config = release
  sandbox_config = release

else ifeq ($(config),dist)
  GLFW_config = dist
  Glad_config = dist
  ImGui_config = dist
  engine_config = dist
  sandbox_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW Glad ImGui engine sandbox

.PHONY: all clean help $(PROJECTS) Dependenices

all: $(PROJECTS)

Dependenices: GLFW Glad ImGui

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C engine/vendor/glfw -f Makefile config=$(GLFW_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C engine/vendor/glad -f Makefile config=$(Glad_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C engine/vendor/imgui -f Makefile config=$(ImGui_config)
endif

engine: GLFW Glad ImGui
ifneq (,$(engine_config))
	@echo "==== Building engine ($(engine_config)) ===="
	@${MAKE} --no-print-directory -C engine -f Makefile config=$(engine_config)
endif

sandbox: engine
ifneq (,$(sandbox_config))
	@echo "==== Building sandbox ($(sandbox_config)) ===="
	@${MAKE} --no-print-directory -C sandbox -f Makefile config=$(sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C engine/vendor/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C engine/vendor/glad -f Makefile clean
	@${MAKE} --no-print-directory -C engine/vendor/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C engine -f Makefile clean
	@${MAKE} --no-print-directory -C sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   Glad"
	@echo "   ImGui"
	@echo "   engine"
	@echo "   sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"